name: Back

on:
      push:
            branches: [develop, back]
            

      pull_request:
            branches:
                  - main
            paths:
                  - 'back/**'
            types: [opened, synchronize, reopened]

jobs:
      back-tests:
            runs-on: ubuntu-latest
            defaults:
                  run:
                        working-directory: back
            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4

                  - name: Set up Java JDK
                    uses: actions/setup-java@v4
                    with:
                          distribution: temurin
                          java-version: 11
                  - name: Build project
                    run: mvn clean install

                  - name: Run tests
                    run: mvn verify -Dspring.profiles=test

                  - name: Generate JaCoCo reports
                    run: mvn test -Dspring.profiles=test

                  - name: Upload JaCoCo reports
                    uses: actions/upload-artifact@v4
                    with:
                          name: jacoco-reports
                          path: back/target/site/jacoco/*

      build:
            name: Build and analyze back
            runs-on: ubuntu-latest
            needs: [back-tests]
            defaults:
                  run:
                        working-directory: back

            steps:
                  - uses: actions/checkout@v4
                    with:
                          fetch-depth: 0
                  - name: Set up JDK 17
                    uses: actions/setup-java@v1
                    with:
                          java-version: 17
                  - name: Cache SonarQube packages
                    uses: actions/cache@v1
                    with:
                          path: ~/.sonar/cache
                          key: ${{ runner.os }}-sonar
                          restore-keys: ${{ runner.os }}-sonar
                  - name: Cache Maven packages
                    uses: actions/cache@v1
                    with:
                          path: ~/.m2
                          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                          restore-keys: ${{ runner.os }}-m2
      push-back:
            name: Push to back branch
            runs-on: ubuntu-latest
            needs: [build]
            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4
                    with:
                          ref: develop
                  - name: Configure Git
                    run: |
                          git config --local user.email "julienfaujanet@gmail.com"
                          git config --local user.name "JulienFAUJA"

                  - name: Commit the changes
                    run: |
                          git checkout -B back
                          if [ -n "$(git status --porcelain back/)" ]; then
                            git pull origin back || true
                            git add back/
                            git commit -m "Update back"
                            git push origin back --force
                          fi

      
      docker:
            name: Docker back
            runs-on: ubuntu-latest
            needs: [build, push-back]
            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4
                  - name: Set up QEMU
                    uses: docker/setup-qemu-action@v3
                  - name: Set up Docker Buildx
                    uses: docker/setup-buildx-action@v3
                  - name: Login to Docker Hub
                    uses: docker/login-action@v3
                    with:
                          username: ${{ secrets.DOCKERHUB_USERNAME }}
                          password: ${{ secrets.DOCKERHUB_TOKEN }}
                  - name: Build and push
                    uses: docker/build-push-action@v6
                    with:
                          context: ./back
                          file: ./back/Dockerfile
                          push: true
                          tags: jufau/bobapp:latest
