name: Back

on:
      push:
            branches:
                  - develop
            paths:
                  - 'back/**'

      pull_request:
            branches:
                  - main
            paths:
                  - 'back/**'
            types: [opened, synchronize, reopened]

jobs:
      build_and_tests:
            runs-on: ubuntu-latest
            defaults:
                  run:
                        working-directory: back
            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4

                  - name: Set up Java JDK
                    uses: actions/setup-java@v4
                    with:
                          distribution: temurin
                          java-version: 11
                  - name: Build and test project
                    run: mvn clean install

                  - name: Upload JaCoCo reports
                    uses: actions/upload-artifact@v4
                    with:
                          name: jacoco-reports
                          path: back/target/site/jacoco/*

      sonar_analyze:
            name: Build and analyze back
            runs-on: self-hosted
            needs: [build_and_tests]
            defaults:
                  run:
                        working-directory: back

            steps:
                  - uses: actions/checkout@v4
                    with:
                          fetch-depth: 0
                  - name: Set up JDK 17
                    uses: actions/setup-java@v1
                    with:
                          java-version: 17
                  - name: Cache SonarQube packages
                    uses: actions/cache@v1
                    with:
                          path: ~/.sonar/cache
                          key: ${{ runner.os }}-sonar
                          restore-keys: ${{ runner.os }}-sonar
                  - name: Cache Maven packages
                    uses: actions/cache@v1
                    with:
                          path: ~/.m2
                          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                          restore-keys: ${{ runner.os }}-m2
                  - name: SonarCloud
                    env:
                      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
                      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
                    run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      docker:
            name: Docker back
            runs-on: ubuntu-latest
            needs: [sonar_analyze]
            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4
                  - name: Set up QEMU
                    uses: docker/setup-qemu-action@v3
                  - name: Set up Docker Buildx
                    uses: docker/setup-buildx-action@v3
                  - name: Login to Docker Hub
                    uses: docker/login-action@v3
                    with:
                          username: ${{ secrets.DOCKERHUB_USERNAME }}
                          password: ${{ secrets.DOCKERHUB_TOKEN }}
                  - name: Build and push
                    uses: docker/build-push-action@v6
                    with:
                          context: ./back
                          file: ./back/Dockerfile
                          push: true
                          tags: jufau/bobapp_back:latest
