name: Front
on:
      push:
            branches: [develop, front]
            

      pull_request:
            branches: [develop, front, main]

            paths:
                  - 'front/**'
            types: [opened, synchronize, reopened]

jobs:
      ci:
            name: CI
            runs-on: ubuntu-latest
            strategy:
                  matrix:
                        node-version: [20]
            steps:
                  - name: Check source code
                    uses: actions/checkout@v4

                  - name: Setup Node
                    uses: actions/setup-node@v4
                    with:
                          node-version: 20
                          cache: 'npm'
                          cache-dependency-path: front/package-lock.json

                  - name: Install dependencies
                    run: npm ci
                    working-directory: front

                  - name: Run tests
                    run: npm run test:prod # --browsers=ChromeHeadlessNoSandbox
                    working-directory: front

                  - name: Upload report
                    uses: actions/upload-artifact@v4
                    with:
                          name: karma-report
                          path: front/coverage/bobapp
      push-front:
            name: Push to front branch
            runs-on: ubuntu-latest
            needs: [ci]
            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4
                    with:
                          ref: develop
                  - name: Configure Git
                    run: |
                          git config --global user.email "julienfaujanet@gmail.com"
                          git config --global user.name "JulienFAUJA"

                  - name: Commit changes
                    run: |
                          git checkout -B front
                          if [ -n "$(git status --porcelain front/)" ]; then
                                git pull origin front || true
                                git add front/
                                git commit -m "Update front"
                                git push origin front --force
                          fi

      
      docker:
            name: Docker front
            runs-on: ubuntu-latest
            needs: [push-front]
            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4
                  - name: Set up QEMU
                    uses: docker/setup-qemu-action@v3
                  - name: Set up Docker Buildx
                    uses: docker/setup-buildx-action@v3
                  - name: Login to Docker Hub
                    uses: docker/login-action@v3
                    with:
                          username: ${{ secrets.DOCKERHUB_USERNAME }}
                          password: ${{ secrets.DOCKERHUB_TOKEN }}
                  - name: Build and push
                    uses: docker/build-push-action@v6
                    with:
                          context: ./front
                          file: ./front/Dockerfile
                          push: true
                          tags: jufau/bobapp:latest
