name: Front
on:
      push:
            branches:
                  - develop
            paths:
                  - 'front/**'

      pull_request:
            branches:
                  - main

            paths:
                  - 'front/**'
            types: [opened, synchronize, reopened]

jobs:
      ci:
            name: CI
            runs-on: ubuntu-latest
            strategy:
                  matrix:
                        node-version: [20]
            steps:
                  - name: Check source code
                    uses: actions/checkout@v4

                  - name: Setup Node
                    uses: actions/setup-node@v4
                    with:
                          node-version: 20
                          cache: 'npm'
                          cache-dependency-path: front/package-lock.json

                  - name: Install dependencies
                    run: npm ci
                    working-directory: front

                  - name: Run tests
                    run: npm run test:prod #--browsers=ChromeHeadlessNoSandbox
                    working-directory: front

                  - name: Upload report
                    uses: actions/upload-artifact@v4
                    with:
                          name: karma-report
                          path: front/coverage/bobapp
                  - name: Push Karma report
                    uses: ad-m/github-push-action@master
                    with:
                          github_token: ${{ secrets.GITHUB_TOKEN }}
                          branch: develop
      sonarcloud:
            runs-on: self-hosted
            needs: [ci]
            steps:
                  - uses: actions/checkout@v4
                  - name: Setup Node for Web project
                    uses: actions/setup-node@v4
                    with:
                          node-version: '20'
                          cache: 'npm'
                          cache-dependency-path: front/package-lock.json
                  - name: Install SonarQube Scanner
                    run: npm install -g sonarqube-scanner
                  - name: Run SonarQube scan
                    env:
                          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
                          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
                    run: >
                          sonar-scanner
                    working-directory: front
      docker:
            name: Docker front
            runs-on: ubuntu-latest
            needs: [sonarcloud]
            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4
                  #- name: Set up QEMU
                    #uses: docker/setup-qemu-action@v3
                  - name: Login to Docker Hub
                    uses: docker/login-action@v3
                    with:
                          username: ${{ secrets.DOCKERHUB_USERNAME }}
                          password: ${{ secrets.DOCKERHUB_TOKEN }}
                  - name: Set up Docker Buildx
                    uses: docker/setup-buildx-action@v3
                  
                  - name: Build and push
                    uses: docker/build-push-action@v6
                    with:
                          context: ./front
                          file: ./front/Dockerfile
                          push: true
                          tags: jufau/bobapp_front:latest
